version: '3'
services:
  angular-ui:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - ./ClientApp:/usr/src/app
       - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200